### ISSUE TITLE
no such table: sms

### ISSUE THREAD

**Issue by metaMMA** [alexlance/signal-message-changer#3]
Backup was created on a phone running Android 13 and Signal version 6.13.7.
Backup was transferred to computer and repo was downloaded as zip file.
Zip file was extracted, and terminal opened in the directory containing the python file and make file.
Backup was copied to this directory and backup file name was exported, as well as the passphrase.

After executing `make run`, the terminal shows the following output:
```
Read entire backup file...

done!

Exporting backup into 'bits//'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Writing Attachments...
Writing Avatars...
Writing SharedPrefFrame(s)...
Writing KeyValueFrame(s)...
Writing StickerFrames...
Writing EndFrame...
Writing database...
Done!

Traceback (most recent call last):
  File "/root/signal-message-changer.py", line 155, in <module>
    print_num_sms()
  File "/root/signal-message-changer.py", line 30, in print_num_sms
    cursor.execute(q)
sqlite3.OperationalError: no such table: sms
make: *** [Makefile:10: run] Error 1
```
Looking for a way to complete the process successfully.

**Comment by alexlance** [comment]
Okay have added a PR that contains support for the latest version of the Signal database. Feel free to checkout the PR and run the code again. No guarantees with this thing.

https://github.com/alexlance/signal-message-changer/pull/4/files
